/*! \page page14 Íàñòðîéêè ïðîåêòà
<b>Ïðîåêò S8-54</b> \n\n

<b>Target</b> \n
- Read/Only Memory Areas – on-chip – IROM1 : <b>0x8000000 0x100000</b> \n
- Code Generation ARM Compiler : <b>Use default compiler version</b> \n
- Read/Write Memory Areas – on-chip – IRAM1 : <b>0x20000000 0x30000</b> \n
<b>User</b> \n
- After Build/Rebuild – Run#1 : <b>fromelf –bin –output.\s8-54.bin .\objects\s8-54.afx</b> \n
<b>C/C++</b> \n
- Preprocessor Symbols – Define : <b>USE_HAL_DRIVER, STM32F437xx</b> \n
- Language/Code Generation – Optimization : <b>Level 2(-O2)</b> \n
- Language/Code Generation – <b>One ELF Section per Function</b> \n
- Language/Code Generation – Warnings : <b>All Warnings</b> \n
- <b>No Auto Includes</b> \n
- <b>C99 Mode</b> \n
<b>Linker</b> \n
- Report ‘might fail’ Conditions as Errors \n
- R/O Base : 0x08000000 \n
- R/W Base : 0x20000000 \n
- Scatter File : <tt>S8-54.sct</tt> \n
    \code
    ; *************************************************************
    ; *** Scatter-Loading Description File generated by uVision ***
    ; *************************************************************
    LR_IROM1 0x08020000 0x00100000  {    ; load region size_region
      ER_IROM1 0x08020000 0x00100000  {  ; load address = execution ad-dress
       *.o (RESET, +First)
       *(InRoot$$Sections)
       .ANY (+RO)
      }
      RW_IRAM1 0x20000000 0x00030000  {  ; RW data
       .ANY (+RW +ZI)
      }
      RW_IRAM2 0x10000000 0x00010000  {  ; CCM data
       .ANY (CCM_DATA);FOO ccmFoo[1024] __attribute__ ((sec-tion("CCM_DATA")));
       startup_stm32f437xx.o (STACK)
       ;startup_stm32f437xx.o (HEAP)
      }
    }
    \endcode
<b>Debug</b> \n
- CPU DLL : SARMCM3.DLL		Parameter : -REMAP –MPU \n
- Dialog DLL : DCM.DLL		Parameter : -pCM4 \n
- Driver DLL : SARMCM3.DLL	Parameter : -MPU \n
- Dialog DLL : TCM.DLL		Parameter : -pCM4 \n
*/
